name: pop

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["910 915 1", "910 915 2", "910 915 3", "910 915 4", "910 915 5", "910 915 6", "910 915 7", "915 920 8", "915 920 9", "915 920 10", "915 920 11", "915 920 12", "915 920 13", "915 920 14", "920 925 15", "920 925 16", "920 925 17", "920 925 18", "920 925 19", "920 925 20", "920 925 21"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Dependencies
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Depedencies
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
        chmod +x ./setup.sh && ./setup.sh
        sleep 5
        ls -l
    - name: Your current IP address
      run: curl -s http://ipecho.net/plain
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: ./con.ovpn
        echo_config: "false"
        username: "p9851504"
        password: "dHa4jp5eZd"
    - name: Your vpn IP address
      run: curl -s http://ipecho.net/plain
    - name: Run
      run: |
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run-n-login.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit