name: pop

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1840 1845 1", "1840 1845 2", "1840 1845 3", "1840 1845 4", "1840 1845 5", "1840 1845 6", "1840 1845 7", "1845 1850 8", "1845 1850 9", "1845 1850 10", "1845 1850 11", "1845 1850 12", "1845 1850 13", "1845 1850 14", "1850 1855 15", "1850 1855 16", "1850 1855 17", "1850 1855 18", "1850 1855 19", "1850 1855 20", "1850 1855 21"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Dependencies
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Depedencies
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
        chmod +x ./setup.sh && ./setup.sh
        sleep 5
        ls -l
    - name: Your current IP address
      run: curl -s http://ipecho.net/plain
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: ./con.ovpn
        echo_config: "false"
        username: "p0682977"
        password: "PDtGY4Fj7D"
    - name: Your vpn IP address
      run: curl -s http://ipecho.net/plain
    - name: Run
      run: |
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run-n-login.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit