name: pop

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1900 1905 1", "1900 1905 2", "1900 1905 3", "1900 1905 4", "1900 1905 5", "1900 1905 6", "1900 1905 7", "1905 1910 8", "1905 1910 9", "1905 1910 10", "1905 1910 11", "1905 1910 12", "1905 1910 13", "1905 1910 14", "1910 1915 15", "1910 1915 16", "1910 1915 17", "1910 1915 18", "1910 1915 19", "1910 1915 20", "1910 1915 21"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Dependencies
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Depedencies
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
        chmod +x ./setup.sh && ./setup.sh
        sleep 5
        ls -l
    - name: Your current IP address
      run: curl -s http://ipecho.net/plain
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: ./con.ovpn
        echo_config: "false"
        username: "p0682977"
        password: "PDtGY4Fj7D"
    - name: Your vpn IP address
      run: curl -s http://ipecho.net/plain
    - name: Run
      run: |
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run-n-login.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit