name: pop

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["880 885 1", "880 885 2", "880 885 3", "880 885 4", "880 885 5", "880 885 6", "880 885 7", "885 890 8", "885 890 9", "885 890 10", "885 890 11", "885 890 12", "885 890 13", "885 890 14", "890 895 15", "890 895 16", "890 895 17", "890 895 18", "890 895 19", "890 895 20", "890 895 21"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Dependencies
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Depedencies
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
        chmod +x ./setup.sh && ./setup.sh
        sleep 5
        ls -l
    - name: Your current IP address
      run: curl -s http://ipecho.net/plain
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: ./con.ovpn
        echo_config: "false"
        username: "p9851504"
        password: "dHa4jp5eZd"
    - name: Your vpn IP address
      run: curl -s http://ipecho.net/plain
    - name: Run
      run: |
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run-n-login.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit